default:
  golem_name: gs.chainsearch
  golem_version: 0.0.1
  app_title: GS Chain Search
  app_github: https://github.com/timothyslau/gs.chainsearch
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
